### PR TITLE
[ES 7] Added es7 version / bug fixed run es 5,6 from docker

### PR DESCRIPTION
**Pull request by suhyunjeon**
- Added es7 version
- Buf fixed es5,6 from docker
- Added elasticsearch.yml, kibana.yml

### CODE REVIEW

**Comment by olivere** [comment]
Can you please also update the README? It e.g. refers to v5 and v6 only, it uses `seed/01.sh` to describe what's going on, the help output is not updated etc. We need to fix that as well.

**Comment by olivere** [comment]
Also, the CI fails.

**Comment by suhyunjeon** [comment]
@olivere

I will update the README files by es7. 
And as README have here, this only support the go lang 1.11+ versions.
But CI has 1.10.

**Comment by olivere** [comment]
Thanks. I fixed a few issues, but ES 7.x support is coming—finally.

**Pull request closed without merging**
